# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
defaultsJob: &defaults
  docker:
    - image: circleci/node:13.8.0
  working_directory: ~/project

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build:
    <<: *defaults
    steps:
      - checkout
      - run: npm i
      - save_cache:
          paths:
            - "src/node_modules"
          key: react-slingshot-package-{{ checksum "package.json" }}
      - run: npm run lint

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - react-slingshot-package-{{ checksum "package.json" }}
      - run: npm i
      - run:
          name: Run tests
          command: npm run test

  anaylze:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - react-slingshot-package-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm audit

workflows:
  my_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - anaylze:
          requires:
            - test
